name: Promote

on:
  push:
  
jobs:
  Promote-TEST:

    runs-on: ubuntu-latest
    steps:
      ### Setup

      ### Version and Tag
      - name: Default Checkout
        uses: actions/checkout@v3
      - name: Update Version
        run: |
          git config --global user.name "kdahal-ventera"
          git config --global user.email "kdahal@ventera.com"
      
          

      - name: Commit and Tag
        run: |
          git add CHANGELOG.md package.json package-lock.json
          git commit -am 'Update Version for Release'
          git tag -a v${{ env.NEW_VERSION }} -m "v${{ env.NEW_VERSION }}" -f
          git push --tags -f
      ### Create Release PR
      - name: Create Pull Request for Release
        uses: peter-evans/create-pull-request@v3
        with:
          author: "${{ env.GH_USER_NAME }} <${{ env.GH_USER_NAME }}s@users.noreply.github.com>"
          base: main
          branch: build-promotion
          #branch-suffix: short-commit-hash
          committer: "${{ env.GH_USER_NAME }} <${{ env.GH_USER_NAME }}s@users.noreply.github.com>"
          delete-branch: true
          title: 'Release PR'
          body: |
            - Auto-generated PR for Release
            - View CHANGELOG.md for Changes
          assignees: ${{ env.GH_USER_NAME }}
          reviewers: ${{ env.GH_USER_NAME }}
          draft: false
          token: ${{ secrets.VSTART_GPM_AUTH }}

      ### Deploy to Stage

      ### Status Checks
